#!/usr/bin/python3
def raise_exception():
    new_list = []
    x = ""
    return new_list[x]
